Repository GUDHI/gudhi-devel, pull requests merged in 2020-01, with the labels that each got.

#195 Fix #105: Alpha-complex document parameter for the picture
  src/Alpha_complex/doc/Intro_alpha_complex.h
  src/Alpha_complex/doc/alpha_complex_representation.ipe
  src/Alpha_complex/doc/alpha_complex_representation.png
  src/common/doc/main_page.md
  src/python/doc/alpha_complex_sum.inc
  src/python/doc/alpha_complex_user.rst
Labels: 3.1.0

#187 Remove implicit this capture in [=]
  src/Nerve_GIC/include/gudhi/GIC.h
  src/Simplex_tree/include/gudhi/Simplex_tree.h
Labels: 3.1.0

#199 Add scikit-learn as a third party library in installation
  src/python/doc/installation.rst
Labels: doc

#189 Link the doc for subsampling & point file readers, some reorg
  src/python/doc/diagram_readers_ref.rst
  src/python/doc/index.rst
  src/python/doc/point_cloud.rst
  src/python/doc/point_cloud_sum.inc
  src/python/gudhi/off_reader.pyx
  src/python/gudhi/reader_utils.pyx
  src/python/gudhi/subsampling.pyx
Labels: 3.2.0

#213 Use mutex from stl instead of tbb one that is deprecated
  src/Nerve_GIC/include/gudhi/GIC.h
  src/Tangential_complex/include/gudhi/Tangential_complex.h
Labels: 3.2.0
