Repository GUDHI/gudhi-devel, pull requests merged in 2022-11, with the labels that each got.

#713 Stores vertices on init_from_range and insert all of them in the Simplex_tree to avoid quadratic behavior
  src/Alpha_complex/include/gudhi/Alpha_complex.h
Labels: optimization, 3.7.0

#717 Translate n_jobs to workers for SciPy
  src/python/doc/installation.rst
  src/python/gudhi/point_cloud/knn.py
Labels: 3.7.0

#721 Use fetch_spiral_2d in the doc
  src/python/doc/clustering.rst
Labels: 3.7.0

#710 Bottleneck distance issue #701 fix
  src/Bottleneck_distance/include/gudhi/Persistence_graph.h
  src/Bottleneck_distance/test/bottleneck_unit_test.cpp
  src/Spatial_searching/example/example_spatial_searching.cpp
  src/Spatial_searching/test/test_Kd_tree_search.cpp
Labels: 3.7.0

#726 Remove spiral 2d as it can be fetch from python interface
  data/points/spiral_2d.csv
Labels: 3.7.0

#727 New write_points_to_off_file
  src/python/CMakeLists.txt
  src/python/doc/installation.rst
  src/python/doc/point_cloud.rst
  src/python/gudhi/off_utils.pyx
  src/python/test/test_off.py
  src/python/test/test_subsampling.py
Labels: 3.7.0

#725 Make RipsComplex construction less confusing
  .github/next_release.md
  src/python/gudhi/rips_complex.pyx
  src/python/test/test_simplex_generators.py
Labels: 3.7.0

#729 Handle QGLViewer >= 2.7.0
  src/GudhUI/view/Viewer.cpp
Labels: 3.7.0

#741 Rename argument of expansion
  src/python/gudhi/simplex_tree.pyx
Labels: 3.7.0

#746 Catch warnings in wasserstein test
  src/python/test/test_wasserstein_distance.py
Labels: 3.7.0

#751 Handle clang warnings
  src/Tangential_complex/include/gudhi/Tangential_complex.h
  src/python/include/Alpha_complex_factory.h
Labels: 3.7.0

#753 Python module should not be compiled if numpy is not found
  src/python/CMakeLists.txt
Labels: build

#737 Fall back to Hera's bottleneck in Nerve_GIC
  .circleci/config.yml
  src/Nerve_GIC/example/CMakeLists.txt
  src/Nerve_GIC/include/gudhi/GIC.h
  src/Nerve_GIC/test/CMakeLists.txt
  src/Nerve_GIC/utilities/CMakeLists.txt
  src/cmake/modules/GUDHI_submodules.cmake
  src/python/CMakeLists.txt
  src/python/setup.py.in
Labels: 3.7.0

#754 Insert vertices first
  src/python/gudhi/simplex_tree.pxd
  src/python/gudhi/simplex_tree.pyx
Labels: 3.7.0
