Repository GUDHI/gudhi-devel, pull requests merged in 2022-09, with the labels that each got.

#658 try ninja for osx
  azure-pipelines.yml
Labels: build, 3.7.0

#680 Fixing bad newshape argument in sklearn cubical example
  src/python/doc/cubical_complex_sklearn_itf_ref.rst
Labels: doc, 3.7.0

#673 Obsolete doxygen settings
  src/Doxyfile.in
Labels: 3.7.0
