Repository GUDHI/gudhi-devel, pull requests merged in 2022-10, with the labels that each got.

#686 Spelling corrections
  src/Contraction/example/Rips_contraction.cpp
  src/Contraction/include/gudhi/Edge_contraction.h
  src/GudhUI/view/Viewer_instructor.h
  src/Persistence_representations/test/persistence_lanscapes_test.cpp
  src/Persistent_cohomology/include/gudhi/Persistent_cohomology.h
  src/Skeleton_blocker/include/gudhi/Skeleton_blocker_complex.h
  src/Skeleton_blocker/include/gudhi/Skeleton_blocker_link_complex.h
  src/cmake/modules/GUDHI_options.cmake
  src/python/gudhi/tensorflow/cubical_layer.py
Labels: 3.7.0

#698 Translate french comment
  src/Skeleton_blocker/include/gudhi/Skeleton_blocker/Skeleton_blocker_sub_complex.h
Labels: 3.7.0

#699 Some doxygen details
  src/Doxyfile.in
  src/common/doc/installation.h
Labels: 3.7.0

#697 c++17 as a new standard to compile the library
  .github/next_release.md
  src/Tangential_complex/benchmark/XML_exporter.h
  src/cmake/modules/GUDHI_compilation_flags.cmake
  src/common/doc/installation.h
  src/python/doc/installation.rst
Labels: build, 3.7.0

#704 Cech_persistence utility for safe/exact/fast mode
  src/Cech_complex/utilities/CMakeLists.txt
  src/Cech_complex/utilities/cech_persistence.cpp
  src/Cech_complex/utilities/cechcomplex.md
Labels: enhancement

#706 Fix badly centered barcode
  src/python/gudhi/persistence_graphical_tools.py
Labels: 3.7.0

#708 Split alpha-complex unit test in 2 files
  src/Alpha_complex/test/Alpha_complex_dim3_unit_test.cpp
  src/Alpha_complex/test/Alpha_complex_unit_test.cpp
  src/Alpha_complex/test/CMakeLists.txt
Labels: 3.7.0

#711 persistence diagram default output is std::cout, not std::clog. Modify utilities help to be in agreement with this
  src/Alpha_complex/utilities/alpha_complex_3d_persistence.cpp
  src/Alpha_complex/utilities/alpha_complex_persistence.cpp
  src/Cech_complex/utilities/cech_persistence.cpp
  src/Collapse/utilities/distance_matrix_edge_collapse_rips_persistence.cpp
  src/Collapse/utilities/point_cloud_edge_collapse_rips_persistence.cpp
  src/Persistent_cohomology/example/persistence_from_file.cpp
  src/Persistent_cohomology/example/rips_multifield_persistence.cpp
  src/Persistent_cohomology/example/rips_persistence_step_by_step.cpp
  src/Persistent_cohomology/example/rips_persistence_via_boundary_matrix.cpp
  src/Rips_complex/utilities/rips_correlation_matrix_persistence.cpp
  src/Rips_complex/utilities/rips_distance_matrix_persistence.cpp
  src/Rips_complex/utilities/rips_persistence.cpp
  src/Rips_complex/utilities/sparse_rips_persistence.cpp
  src/Witness_complex/utilities/strong_witness_persistence.cpp
  src/Witness_complex/utilities/weak_witness_persistence.cpp
  src/Witness_complex/utilities/witnesscomplex.md
Labels: doc, 3.7.0

#714 Use std::optional to check C++17 support
  src/Tangential_complex/include/gudhi/Tangential_complex.h
  src/cmake/modules/GUDHI_compilation_flags.cmake
  src/python/CMakeLists.txt
Labels: 3.7.0
