Repository GUDHI/gudhi-devel, pull requests merged in 2022-08, with the labels that each got.

#661 [Doc] Modify doc in simplex_tree in order to match code
  src/python/gudhi/simplex_tree.pyx
Labels: doc, 3.6.0

#650 [Cech] Assign to sh same key as face
  src/Cech_complex/include/gudhi/Cech_complex_blocker.h
Labels: optimization, 3.6.0

#668 [Cech] Check filtration validity
  src/Cech_complex/include/gudhi/Cech_complex_blocker.h
Labels: 3.6.0

#584 A bug in the Entropy function has been solved
  src/python/gudhi/representations/vector_methods.py
  src/python/test/test_representations.py
Labels: bug, 3.6.0

#670 Adapt the use of CGAL::Modifiable_priority_queue for CGAL>=5.5 while keeping compatibility
  src/Contraction/include/gudhi/Skeleton_blocker_contractor.h
Labels: bug, 3.6.0

#675 Release note 3.6.0
  .github/next_release.md
  CMakeGUDHIVersion.txt
  src/python/doc/cubical_complex_sklearn_itf_ref.rst
  src/python/doc/cubical_complex_sum.inc
  src/python/doc/differentiation_sum.inc
  src/python/doc/persistent_cohomology_user.rst
  src/python/doc/rips_complex_sum.inc
  src/python/doc/rips_complex_user.rst
  src/python/doc/simplex_tree_sum.inc
Labels: 3.6.0

#677 Release 3.6.0rc2
  .github/next_release.md
  .github/workflows/pip-packaging-windows.yml
  CMakeGUDHIVersion.txt
Labels: 3.6.0

#678 Release 3 6 0
  .github/next_release.md
  CMakeGUDHIVersion.txt
  src/python/doc/img/tensorflow.png
Labels: 3.6.0
