Repository GUDHI/gudhi-devel, pull requests merged in 2023-03, with the labels that each got.

#731 Alternative version of choose_n_farthest_points
  .github/next_release.md
  biblio/bibliography.bib
  biblio/how_to_cite_gudhi.bib.in
  src/Rips_complex/include/gudhi/Sparse_rips_complex.h
  src/Rips_complex/test/test_rips_complex.cpp
  src/Subsampling/doc/Intro_subsampling.h
  src/Subsampling/include/gudhi/choose_n_farthest_points.h
  src/Subsampling/test/test_choose_n_farthest_points.cpp
  src/common/doc/main_page.md
  src/python/gudhi/subsampling.pyx
  src/python/include/Subsampling_interface.h
  src/python/test/test_subsampling.py
Labels: 3.8.0

#784 New function to compute persistence of a function on ℝ
  biblio/bibliography.bib
  biblio/test/test_biblio.tex
  src/Persistent_cohomology/benchmark/CMakeLists.txt
  src/Persistent_cohomology/benchmark/line.cpp
  src/Persistent_cohomology/doc/Intro_persistent_cohomology.h
  src/Persistent_cohomology/example/CMakeLists.txt
  src/Persistent_cohomology/example/persistence_on_a_line.cpp
  src/Persistent_cohomology/include/gudhi/Persistence_on_a_line.h
Labels: 3.8.0

#781 Speed-up persistence of 1d cubical complex
  src/Bitmap_cubical_complex/include/gudhi/Bitmap_cubical_complex_base.h
  src/Bitmap_cubical_complex/include/gudhi/Bitmap_cubical_complex_periodic_boundary_conditions_base.h
  src/Persistent_cohomology/include/gudhi/Persistent_cohomology.h
Labels: 3.8.0

#803 Sphinx fix layout
  .circleci/config.yml
  .github/for_maintainers/new_gudhi_version_creation.md
  .github/for_maintainers/switcher.json
  src/python/doc/_static/python_gudhi.css
  src/python/doc/_templates/layout.html
  src/python/doc/_templates/navbar_center_gudhi.html
  src/python/doc/_templates/navbar_end_gudhi.html
  src/python/doc/_templates/navbar_start_gudhi.html
  src/python/doc/_templates/search-gudhi-field.html
  src/python/doc/_templates/sidebar-gudhi.html
  src/python/doc/bottleneck_distance_sum.inc
  src/python/doc/conf.py
  src/python/doc/cubical_complex_sum.inc
  src/python/doc/persistence_graphical_tools_sum.inc
  src/python/doc/representations_sum.inc
  src/python/doc/rips_complex_sum.inc
  src/python/doc/simplex_tree_sum.inc
  src/python/doc/todos.rst
  src/python/doc/wasserstein_distance_sum.inc
Labels: 3.8.0

#827 Consistent name between doc and code
  src/Subsampling/include/gudhi/choose_n_farthest_points.h
Labels: 3.8.0

#835 Modify python documentation third parties
  src/cmake/modules/GUDHI_third_party_libraries.cmake
  src/python/CMakeLists.txt
  src/python/doc/installation.rst
Labels: doc, 3.8.0

#833 New is_empty for simplex tree
  src/Simplex_tree/include/gudhi/Simplex_tree.h
  src/Simplex_tree/test/simplex_tree_unit_test.cpp
  src/python/gudhi/simplex_tree.pxd
  src/python/gudhi/simplex_tree.pyx
  src/python/test/test_simplex_tree.py
Labels: 3.8.0

#829 Don't crash on bogus assign_filtration
  src/python/gudhi/simplex_tree.pxd
  src/python/include/Simplex_tree_interface.h
  src/python/test/test_simplex_tree.py
Labels: 3.8.0

#832 Avoid crash in Alpha_complex::get_point
  src/Alpha_complex/include/gudhi/Alpha_complex.h
  src/Alpha_complex/test/Alpha_complex_unit_test.cpp
Labels: 3.8.0

#837 Prune above dimension
  src/Simplex_tree/include/gudhi/Simplex_tree.h
  src/Simplex_tree/test/simplex_tree_remove_unit_test.cpp
  src/python/gudhi/simplex_tree.pxd
  src/python/gudhi/simplex_tree.pyx
  src/python/test/test_simplex_tree.py
Labels: 3.8.0

#836 Changes for onetbb use instead of deprecated TBB
  azure-pipelines.yml
  src/Alpha_complex/benchmark/CMakeLists.txt
  src/Alpha_complex/example/CMakeLists.txt
  src/Alpha_complex/test/CMakeLists.txt
  src/Alpha_complex/utilities/CMakeLists.txt
  src/Bitmap_cubical_complex/benchmark/CMakeLists.txt
  src/Bitmap_cubical_complex/example/CMakeLists.txt
  src/Bitmap_cubical_complex/test/CMakeLists.txt
  src/Bitmap_cubical_complex/utilities/CMakeLists.txt
  src/Bottleneck_distance/benchmark/CMakeLists.txt
  src/Bottleneck_distance/example/CMakeLists.txt
  src/Bottleneck_distance/test/CMakeLists.txt
  src/Bottleneck_distance/utilities/CMakeLists.txt
  src/Cech_complex/benchmark/CMakeLists.txt
  src/Cech_complex/example/CMakeLists.txt
  src/Cech_complex/test/CMakeLists.txt
  src/Cech_complex/utilities/CMakeLists.txt
  src/Collapse/example/CMakeLists.txt
  src/Collapse/test/CMakeLists.txt
  src/Collapse/utilities/CMakeLists.txt
  src/GudhUI/CMakeLists.txt
  src/Nerve_GIC/example/CMakeLists.txt
  src/Nerve_GIC/test/CMakeLists.txt
  src/Nerve_GIC/utilities/CMakeLists.txt
  src/Persistence_representations/test/CMakeLists.txt
  src/Persistence_representations/utilities/persistence_intervals/CMakeLists.txt
  src/Persistent_cohomology/benchmark/CMakeLists.txt
  src/Persistent_cohomology/example/CMakeLists.txt
  src/Persistent_cohomology/test/CMakeLists.txt
  src/Rips_complex/example/CMakeLists.txt
  src/Rips_complex/test/CMakeLists.txt
  src/Rips_complex/utilities/CMakeLists.txt
  src/Simplex_tree/example/CMakeLists.txt
  src/Simplex_tree/test/CMakeLists.txt
  src/Tangential_complex/benchmark/CMakeLists.txt
  src/Tangential_complex/benchmark/benchmark_tc.cpp
  src/Tangential_complex/example/CMakeLists.txt
  src/Tangential_complex/include/gudhi/Tangential_complex.h
  src/Tangential_complex/test/CMakeLists.txt
  src/Toplex_map/benchmark/CMakeLists.txt
  src/Witness_complex/example/CMakeLists.txt
  src/Witness_complex/test/CMakeLists.txt
  src/Witness_complex/utilities/CMakeLists.txt
  src/cmake/modules/FindTBB.cmake
  src/cmake/modules/GUDHI_third_party_libraries.cmake
  src/cmake/modules/UseTBB.cmake
  src/common/benchmark/CMakeLists.txt
  src/common/doc/installation.h
  src/python/CMakeLists.txt
  src/python/doc/installation.rst
Labels: 3.8.0

#823 CubicalPersistence: handle 'vertices' input, special case 1d
  src/python/CMakeLists.txt
  src/python/doc/cubical_complex_user.rst
  src/python/gudhi/_persline.cc
  src/python/gudhi/sklearn/cubical_persistence.py
  src/python/test/test_sklearn_cubical_persistence.py
Labels: 3.8.0

#825 Rewrite impose_lower_star_filtration_from_vertices
  src/Bitmap_cubical_complex/include/gudhi/Bitmap_cubical_complex_base.h
Labels: 3.8.0

#842 Qt vs TBB conflict about `emit`
  src/GudhUI/CMakeLists.txt
  src/GudhUI/gui/MainWindow.cpp
  src/GudhUI/gui/Menu_edge_contraction.cpp
  src/GudhUI/gui/Menu_k_nearest_neighbors.cpp
  src/GudhUI/gui/Menu_persistence.cpp
  src/GudhUI/gui/Menu_uniform_neighbors.cpp
  src/GudhUI/view/Viewer.cpp
Labels: bug, 3.8.0

#843 generate long_description for the pip package from cmake
  src/python/CMakeLists.txt
  src/python/introduction.rst
  src/python/setup.py.in
Labels: build

#834 Safer use of disjoint_sets in tomato
  src/python/gudhi/clustering/_tomato.cc
Labels: 3.8.0

#828 Misc cubical simplifications
  src/Bitmap_cubical_complex/include/gudhi/Bitmap_cubical_complex.h
  src/Bitmap_cubical_complex/include/gudhi/Bitmap_cubical_complex_base.h
  src/Bitmap_cubical_complex/include/gudhi/Bitmap_cubical_complex_periodic_boundary_conditions_base.h
  src/Bitmap_cubical_complex/test/Bitmap_test.cpp
Labels: 3.8.0

#845 Remove useless execute permission from python tests
  src/python/test/test_alpha_complex.py
  src/python/test/test_betti_curve_representations.py
  src/python/test/test_bottleneck_distance.py
  src/python/test/test_cover_complex.py
  src/python/test/test_cubical_complex.py
  src/python/test/test_datasets_generators.py
  src/python/test/test_dtm.py
  src/python/test/test_euclidean_witness_complex.py
  src/python/test/test_knn.py
  src/python/test/test_reader_utils.py
  src/python/test/test_representations.py
  src/python/test/test_rips_complex.py
  src/python/test/test_simplex_generators.py
  src/python/test/test_simplex_tree.py
  src/python/test/test_simplex_tree_serialization.py
  src/python/test/test_subsampling.py
  src/python/test/test_tangential_complex.py
  src/python/test/test_time_delay.py
  src/python/test/test_tomato.py
  src/python/test/test_wasserstein_barycenter.py
  src/python/test/test_wasserstein_distance.py
  src/python/test/test_wasserstein_with_tensors.py
  src/python/test/test_witness_complex.py
Labels: 3.8.0

#403 Mapper + GIC wrapper
  src/Nerve_GIC/include/gudhi/GIC.h
  src/Nerve_GIC/utilities/KeplerMapperVisuFromTxtFile.py
  src/python/CMakeLists.txt
  src/python/doc/cover_complex_sklearn_isk_ref.rst
  src/python/doc/cover_complex_sklearn_user.rst
  src/python/doc/installation.rst
  src/python/doc/nerve_gic_complex_ref.rst
  src/python/doc/nerve_gic_complex_sum.inc
  src/python/doc/nerve_gic_complex_user.rst
  src/python/gudhi/cover_complex.py
  src/python/gudhi/nerve_gic.pyx
  src/python/test/test_cover_complex.py
Labels: 3.8.0
