Repository GUDHI/gudhi-devel, pull requests merged in 2023-09, with the labels that each got.

#956 On OSX, '-mmacosx-version-min=XXX' compile and link options management
  src/python/CMakeLists.txt
Labels: 3.9.0

#958 Some missing includes in Simplex_tree
  src/Simplex_tree/include/gudhi/Simplex_tree.h
  src/Simplex_tree/include/gudhi/Simplex_tree/Simplex_tree_star_simplex_iterators.h
  src/Simplex_tree/test/simplex_tree_ctor_and_move_unit_test.cpp
Labels: 3.9.0

#962 Python documentation requires sphinxcontrib-bibtex to be built
  src/cmake/modules/GUDHI_third_party_libraries.cmake
  src/python/CMakeLists.txt
Labels: doc, 3.9.0

#968 warns if Hera submodule is not initialzied
  src/cmake/modules/GUDHI_submodules.cmake
Labels: build, 3.9.0

#919 Minimum enclosing ball filtration values
  src/Cech_complex/concept/SimplicialComplexForMEB.h
  src/Cech_complex/doc/Intro_cech_complex.h
  src/Cech_complex/include/gudhi/Cech_complex_blocker.h
  src/Cech_complex/include/gudhi/MEB_filtration.h
  src/Cech_complex/test/test_cech_complex.cpp
Labels: 3.9.0

#966 Missing erase after remove_if
  src/Subsampling/benchmark/choose_n_farthest_points.cpp
  src/Subsampling/include/gudhi/choose_n_farthest_points.h
Labels: 3.9.0

#969 missing iostream import
  src/Persistent_cohomology/include/gudhi/Persistent_cohomology.h
Labels: 3.9.0

#971 Fix fast cofaces for insert_batch_vertices
  src/Simplex_tree/include/gudhi/Simplex_tree.h
  src/Simplex_tree/test/simplex_tree_unit_test.cpp
Labels: 3.9.0
