Repository GUDHI/gudhi-devel, pull requests merged in 2023-08, with the labels that each got.

#921 Don't use skeleton_simplex_range in Persistent_cohomology
  src/Persistent_cohomology/include/gudhi/Persistent_cohomology.h
Labels: 3.9.0

#938 Boost 1.71.0 is now the minimal boost required version
  .github/next_release.md
  src/cmake/modules/GUDHI_third_party_libraries.cmake
  src/common/doc/installation.h
  src/python/doc/installation.rst
Labels: build

#940 Rips threshold documentation clarification
  src/Rips_complex/include/gudhi/Rips_complex.h
  src/python/gudhi/rips_complex.pyx
Labels: 3.9.0

#941 small fix to make cmake find OpenGL when OpenGL_GL_PREFERENCE=GLVND
  src/GudhUI/CMakeLists.txt
Labels: build, 3.9.0

#942 Remove __root_source_dir__ from cubical documentation
  src/python/doc/cubical_complex_user.rst
  src/python/gudhi/cubical_complex.pyx
  src/python/gudhi/periodic_cubical_complex.pyx
Labels: doc
