Repository GUDHI/gudhi-devel, pull requests merged in 2023-11, with the labels that each got.

#995 macOS big_sur -> monterey
  scripts/build_osx_universal_gmpfr.sh
Labels: 3.9.0

#1000 Split Alpha_complex_dim3_unit_test for CI purpose
  src/Alpha_complex/test/Alpha_complex_dim3_Epeck_dynamic_unit_test.cpp
  src/Alpha_complex/test/Alpha_complex_dim3_Epeck_static_unit_test.cpp
  src/Alpha_complex/test/Alpha_complex_dim3_Epick_dynamic_unit_test.cpp
  src/Alpha_complex/test/Alpha_complex_dim3_Epick_static_unit_test.cpp
  src/Alpha_complex/test/Alpha_complex_dim3_unit_test.h
  src/Alpha_complex/test/CMakeLists.txt
Labels: CI, 3.9.0

#996 Homogenize `:Requires:` call for python doc render
  src/python/doc/nerve_gic_complex_sum.inc
  src/python/gudhi/dtm_rips_complex.py
Labels: doc

#1001 add GudhUI compilation flag
  CMakeLists.txt
  src/CMakeLists.txt
  src/cmake/modules/GUDHI_options.cmake
Labels: build, 3.9.0
