Repository GUDHI/gudhi-devel, pull requests merged in 2023-12, with the labels that each got.

#1009 Rename collapse_edges
  src/python/CMakeLists.txt
  src/python/doc/edge_collapse.rst
  src/python/doc/rips_complex_user.rst
  src/python/gudhi/flag_filtration/__init__.py
  src/python/gudhi/flag_filtration/edge_collapse.py
  src/python/test/test_collapse_edges.py
Labels: Required for 3.9.0

#1006 Try python 3.12 in CI
  .github/workflows/pip-build-linux.yml
  .github/workflows/pip-build-windows.yml
  .github/workflows/pip-packaging-linux.yml
  .github/workflows/pip-packaging-osx.yml
  .github/workflows/pip-packaging-windows.yml
Labels: 3.9.0

#1005 Release note for simplex tree options
  .github/next_release.md
  src/Cech_complex/doc/Intro_cech_complex.h
Labels: doc, 3.9.0, Required for 3.9.0

#1011 GUDHI version 3.9.0
  .github/for_maintainers/switcher.json
  CMakeGUDHIVersion.txt
Labels: 3.9.0

#1012 Prepare next release 3.10.0a1
  .github/next_release.md
  CMakeGUDHIVersion.txt
Labels: 3.10.0
