Repository GUDHI/gudhi-devel, pull requests merged in 2024-09, with the labels that each got.

#1129 Fix Betti numbers on isolated zero simplices segfault and test it
  src/Persistent_cohomology/include/gudhi/Persistent_cohomology.h
  src/Persistent_cohomology/test/betti_numbers_unit_test.cpp
Labels: bug, 3.11.0

#1131 Symbolic links for cython and pybind11 compilation
  .github/for_maintainers/new_gudhi_version_creation.md
  .github/workflows/pip-packaging-linux.yml
  .gitignore
  src/python/CMakeLists.txt
  src/python/setup.py.in
Labels: build

#1132 copy_on_error if symbolic link failed to be created
  src/python/CMakeLists.txt
Labels: build, 3.11.0

#1134 [Persistence matrix] renaming matrix cells as matrix entries
  src/Persistence_matrix/concept/PersistenceMatrixColumn.h
  src/Persistence_matrix/concept/PersistenceMatrixOptions.h
  src/Persistence_matrix/include/gudhi/Matrix.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/Base_matrix.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/Base_matrix_with_column_compression.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/Boundary_matrix.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/Chain_matrix.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/Id_to_index_overlay.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/Position_to_index_overlay.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/RU_matrix.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/allocators/cell_constructors.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/allocators/entry_constructors.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/base_swap.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/chain_vine_swap.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/cell_types.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/column_utilities.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/entry_types.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/heap_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/intrusive_list_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/intrusive_set_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/list_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/naive_vector_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/row_access.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/set_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/unordered_set_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/vector_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/matrix_row_access.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/ru_rep_cycles.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/ru_vine_swap.h
  src/Persistence_matrix/include/gudhi/persistence_matrix_options.h
  src/Persistence_matrix/test/pm_column_tests.h
  src/Persistence_matrix/test/pm_column_tests_mastermatrix.h
  src/Persistence_matrix/test/pm_matrix_tests.h
  src/Persistence_matrix/test/pm_test_utilities.h
  src/Persistence_matrix/test/test_persistence_matrix_matrix_z2_base.cpp
  src/Persistence_matrix/test/test_persistence_matrix_matrix_z2_compression.cpp
  src/Persistence_matrix/test/test_persistence_matrix_matrix_zp_base.cpp
  src/Persistence_matrix/test/test_persistence_matrix_matrix_zp_compression.cpp
Labels: 3.11.0

#1135 Cmake improvement with importlib metadata
  .github/next_release.md
  src/cmake/modules/GUDHI_third_party_libraries.cmake
  src/python/CMakeLists.txt
  src/python/doc/installation.rst
  src/python/setup.py.in
Labels: enhancement, build, python3.8
