Repository GUDHI/gudhi-devel, pull requests merged in 2024-06, with the labels that each got.

#1061 Fix for #1022
  src/python/gudhi/representations/vector_methods.py
Labels: 3.10.0

#1066 Only vcpkg release libs on CI
  azure-pipelines.yml
Labels: CI

#1070 review CGAL and Eigen requirements in doc
  src/common/doc/main_page.md
  src/python/doc/alpha_complex_sum.inc
  src/python/doc/bottleneck_distance_sum.inc
  src/python/doc/cover_complex_sklearn_user.rst
  src/python/doc/datasets.inc
  src/python/doc/installation.rst
  src/python/doc/nerve_gic_complex_sum.inc
  src/python/doc/point_cloud_sum.inc
  src/python/doc/rips_complex_sum.inc
  src/python/doc/tangential_complex_sum.inc
  src/python/doc/witness_complex_sum.inc
  src/python/gudhi/representations/metrics.py
Labels: 3.10.0

#1072 Tweak default parameters of KMeans in Atol
  src/python/gudhi/representations/vector_methods.py
Labels: 3.10.0

#1073 Rescale values for KDE to avoir underflow
  src/python/gudhi/clustering/tomato.py
  src/python/test/test_tomato.py
Labels: 3.10.0

#1080 code review: gimp was bluring image
  src/Persistence_matrix/doc/persistence_matrix.ipe
  src/Persistence_matrix/doc/persistence_matrix.png
Labels: 3.10.0

#1084 Fix CI for numpy 2.X support
  .circleci/config.yml
  .github/workflows/pip-build-linux.yml
  .github/workflows/pip-build-osx.yml
  .github/workflows/pip-build-windows.yml
  .github/workflows/pip-packaging-linux.yml
  .github/workflows/pip-packaging-osx.yml
  .github/workflows/pip-packaging-windows.yml
  azure-pipelines.yml
Labels: CI, 3.10.0

#1087 GUDHI 3.9.0 Release candidate 2
  .github/changelog.md
  .github/for_maintainers/switcher.json
  CMakeGUDHIVersion.txt
Labels: 3.10.0

#1089 Fix pip wheels build
  .github/workflows/pip-packaging-linux.yml
  .github/workflows/pip-packaging-osx.yml
  .github/workflows/pip-packaging-windows.yml
Labels: CI, 3.10.0

#1090 GUDHI Release 3.10.0
  .github/for_maintainers/switcher.json
  CMakeGUDHIVersion.txt
Labels: 3.10.0

#1094 Workaround boost::optional that became std::optional on CGAL 6.X
  src/Contraction/include/gudhi/Skeleton_blocker_contractor.h
Labels: bug
