Repository GUDHI/gudhi-devel, pull requests merged in 2025-02, with the labels that each got.

#1153 [Persistence Matrix] replacing static_cast(-1) by method
  src/Persistence_matrix/concept/PersistenceMatrixColumn.h
  src/Persistence_matrix/include/gudhi/Matrix.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/Base_matrix.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/Base_matrix_with_column_compression.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/Boundary_matrix.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/Chain_matrix.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/Id_to_index_overlay.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/Position_to_index_overlay.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/RU_matrix.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/base_pairing.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/boundary_cell_position_to_id_mapper.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/chain_column_extra_properties.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/column_dimension_holder.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/heap_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/intrusive_list_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/intrusive_set_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/list_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/naive_vector_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/row_access.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/set_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/unordered_set_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/vector_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/matrix_dimension_holders.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/ru_pairing.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/ru_rep_cycles.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/ru_vine_swap.h
  src/Persistence_matrix/test/pm_column_tests.h
  src/Persistence_matrix/test/pm_column_tests_mastermatrix.h
  src/Persistence_matrix/test/pm_matrix_tests.h
Labels: 3.11.0

#1168 No need to test grep command result on doxygen.log file
  .circleci/config.yml
Labels: CI

#1154 [Persistence Matrix] Addition of small vectors as a column type
  src/Persistence_matrix/include/gudhi/Matrix.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/heap_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/intrusive_list_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/intrusive_set_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/list_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/naive_vector_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/set_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/unordered_set_column.h
  src/Persistence_matrix/include/gudhi/Persistence_matrix/columns/vector_column.h
  src/Persistence_matrix/include/gudhi/persistence_matrix_options.h
  src/Persistence_matrix/test/pm_column_tests_boost_type_lists.h
  src/Persistence_matrix/test/pm_common_boost_type_lists.h
  src/Persistence_matrix/test/pm_matrix_tests_boost_type_lists.h
Labels: 3.11.0

#1151 Simplex tree ctors with data
  src/Simplex_tree/include/gudhi/Simplex_tree.h
  src/Simplex_tree/test/CMakeLists.txt
  src/Simplex_tree/test/simplex_tree_data_unit_test.cpp
  src/Simplex_tree/test/simplex_tree_unit_test.cpp
Labels: needed for 3.11.0

#1171 Test 3.13 with numpy 1.26.0
  .github/workflows/pip-build-linux.yml
  .github/workflows/pip-build-osx.yml
  .github/workflows/pip-build-windows.yml
  .github/workflows/pip-packaging-osx.yml
  .github/workflows/pip-packaging-windows.yml
Labels: CI
